// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Admin_getAdminName_6dc55da125_Test {

    private Admin admin;

    @BeforeEach
    public void setUp() {
        admin = new Admin();
    }

    @Test
    public void testGetAdminName_Success() {
        String expectedName = "John Doe";
        admin.setAdminName(expectedName);
        String actualName = admin.getAdminName();
        Assertions.assertEquals(expectedName, actualName, "Admin name should be equal to the set value");
    }

    @Test
    public void testGetAdminName_Null() {
        String actualName = admin.getAdminName();
        Assertions.assertNull(actualName, "Admin name should be null as it is not set");
    }
}
