// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Admin_setAdminEmail_de656ae2b5_Test {

    @InjectMocks
    private Admin admin;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetAdminEmail_ValidEmail() {
        String adminEmail = "admin@example.com";
        admin.setAdminEmail(adminEmail);
        assertEquals(adminEmail, admin.getAdminEmail());
    }

    @Test
    public void testSetAdminEmail_NullEmail() {
        String adminEmail = null;
        admin.setAdminEmail(adminEmail);
        assertEquals(adminEmail, admin.getAdminEmail());
    }
}
