// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Admin_getAdminId_bcb52b5aa3_Test {

    private Admin admin;

    @BeforeEach
    public void setUp() {
        admin = new Admin();
    }

    @Test
    public void testGetAdminId_WhenAdminIdIsSet() {
        int expectedAdminId = 123;
        admin.setAdminId(expectedAdminId);
        assertEquals(expectedAdminId, admin.getAdminId());
    }

    @Test
    public void testGetAdminId_WhenAdminIdIsNotSet() {
        int defaultAdminId = 0;
        assertEquals(defaultAdminId, admin.getAdminId());
    }
}
