// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Admin_setAdminId_a83a201657_Test {

    private Admin admin;

    @BeforeEach
    public void setUp() {
        admin = new Admin();
    }

    @Test
    public void testSetAdminId_PositiveNumber() {
        admin.setAdminId(1234);
        assertEquals(1234, admin.getAdminId(), "Admin ID should be set to 1234");
    }

    @Test
    public void testSetAdminId_Zero() {
        admin.setAdminId(0);
        assertEquals(0, admin.getAdminId(), "Admin ID should be set to 0");
    }

    @Test
    public void testSetAdminId_NegativeNumber() {
        admin.setAdminId(-1234);
        assertEquals(-1234, admin.getAdminId(), "Admin ID should be set to -1234");
    }
}
