// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Admin_getAdminEmail_d02ae8178d_Test {

    @Test
    public void testGetAdminEmail_ValidEmail() {
        Admin admin = new Admin();
        admin.setAdminEmail("admin@example.com");
        String expected = "admin@example.com";
        assertEquals(expected, admin.getAdminEmail());
    }

    @Test
    public void testGetAdminEmail_NullEmail() {
        Admin admin = new Admin();
        admin.setAdminEmail(null);
        assertNull(admin.getAdminEmail());
    }
}
