// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Admin_getAdminNumber_5a70a34bd3_Test {

    @InjectMocks
    Admin admin;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        admin.setAdminNumber("1234567890");
    }

    @Test
    public void testGetAdminNumber() {
        String expected = "1234567890";
        String actual = admin.getAdminNumber();
        Assertions.assertEquals(expected, actual, "Admin number should be equal to 1234567890");
    }

    @Test
    public void testGetAdminNumber_fail() {
        String expected = "0987654321";
        String actual = admin.getAdminNumber();
        Assertions.assertNotEquals(expected, actual, "Admin number should not be equal to 0987654321");
    }
}
