// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Admin_getAdminPassword_0e8a55cd7c_Test {

    private Admin admin;

    @BeforeEach
    public void setUp() {
        admin = new Admin();
    }

    @Test
    public void testGetAdminPassword_WhenPasswordIsSet() {
        String expectedPassword = "admin123";
        admin.setAdminPassword(expectedPassword);

        String actualPassword = admin.getAdminPassword();

        assertEquals(expectedPassword, actualPassword, "The expected password did not match the actual password.");
    }

    @Test
    public void testGetAdminPassword_WhenPasswordIsNotSet() {
        String actualPassword = admin.getAdminPassword();

        assertNull(actualPassword, "The password should be null as it has not been set yet.");
    }
}
