// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Admin_setAdminPassword_26e40ce4d3_Test {

    private Admin admin;

    @BeforeEach
    void init() {
        admin = new Admin();
    }

    @Test
    public void testSetAdminPassword() {
        String password = "SecurePassword123";
        admin.setAdminPassword(password);
        assertEquals(password, admin.getAdminPassword());
    }

    @Test
    public void testSetAdminPasswordNull() {
        String password = null;
        admin.setAdminPassword(password);
        assertNull(admin.getAdminPassword());
    }

}
