// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Admin_getAdminNumber_5a70a34bd3_Test {

    @InjectMocks
    Admin admin;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetAdminNumberWhenAdminNumberIsNotNull() {
        admin.setAdminNumber("1234567890");
        String adminNumber = admin.getAdminNumber();
        assertNotNull(adminNumber);
        assertEquals("1234567890", adminNumber);
    }

    @Test
    public void testGetAdminNumberWhenAdminNumberIsNull() {
        admin.setAdminNumber(null);
        String adminNumber = admin.getAdminNumber();
        assertNull(adminNumber);
    }
}
