// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Admin_setAdminName_8524acc886_Test {

    @Test
    public void testSetAdminNameValid() {
        Admin admin = new Admin();
        String expectedAdminName = "John Doe";
        admin.setAdminName(expectedAdminName);
        assertEquals(expectedAdminName, admin.getAdminName());
    }

    @Test
    public void testSetAdminNameNull() {
        Admin admin = new Admin();
        String expectedAdminName = null;
        admin.setAdminName(expectedAdminName);
        assertNull(admin.getAdminName());
    }
}
