// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Admin_getAdminEmail_d02ae8178d_Test {

    @Test
    public void testGetAdminEmail() {
        Admin admin = new Admin();

        // Test case 1: When the email is set to a valid email address
        String validEmail = "admin@business.com";
        admin.setAdminEmail(validEmail);
        assertEquals(validEmail, admin.getAdminEmail(), "Expected email to be " + validEmail);

        // Test case 2: When the email is set to null
        admin.setAdminEmail(null);
        assertNull(admin.getAdminEmail(), "Expected email to be null");
    }
}
