// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Admin_setAdminName_8524acc886_Test {

    private Admin admin;

    @BeforeEach
    public void setUp() {
        admin = new Admin();
    }

    @Test
    public void testSetAdminName_ValidName() {
        String adminName = "John Doe";
        admin.setAdminName(adminName);
        assertEquals(adminName, admin.getAdminName());
    }

    @Test
    public void testSetAdminName_NullName() {
        String adminName = null;
        admin.setAdminName(adminName);
        assertNull(admin.getAdminName());
    }

    @Test
    public void testSetAdminName_EmptyName() {
        String adminName = "";
        admin.setAdminName(adminName);
        assertEquals(adminName, admin.getAdminName());
    }
}
