// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(SpringExtension.class)
public class Admin_setAdminEmail_de656ae2b5_Test {

    private Admin admin;

    @BeforeEach
    public void setUp() {
        admin = new Admin();
    }

    @Test
    public void testSetAdminEmail_ValidEmail() {
        String adminEmail = "admin@test.com";
        admin.setAdminEmail(adminEmail);

        assertEquals(adminEmail, admin.getAdminEmail(), "The admin email should match the set value.");
    }

    @Test
    public void testSetAdminEmail_EmptyString() {
        String adminEmail = "";
        admin.setAdminEmail(adminEmail);

        assertEquals(adminEmail, admin.getAdminEmail(), "The admin email should match the set value even if it is an empty string.");
    }
}
