// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Admin_setAdminNumber_30bda3157c_Test {

    private Admin admin;

    @BeforeEach
    public void setup() {
        admin = new Admin();
    }

    @Test
    public void testSetAdminNumber_ValidNumber() {
        String validAdminNumber = "1234567890";
        admin.setAdminNumber(validAdminNumber);
        Assertions.assertEquals(validAdminNumber, admin.getAdminNumber());
    }

    @Test
    public void testSetAdminNumber_NullNumber() {
        admin.setAdminNumber(null);
        Assertions.assertNull(admin.getAdminNumber());
    }

    @Test
    public void testSetAdminNumber_EmptyNumber() {
        admin.setAdminNumber("");
        Assertions.assertEquals("", admin.getAdminNumber());
    }

    @Test
    public void testSetAdminNumber_WhiteSpaceNumber() {
        admin.setAdminNumber(" ");
        Assertions.assertEquals(" ", admin.getAdminNumber());
    }
}
