// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class Orders_getoQuantity_7e757e0c91_Test {

    @MockBean
    private Order order;

    @Test
    public void testGetoQuantitySuccess() {
        int expectedQuantity = 5;
        when(order.getoQuantity()).thenReturn(expectedQuantity);
        int actualQuantity = order.getoQuantity();
        assertEquals(expectedQuantity, actualQuantity, "Expected quantity does not match actual quantity");
    }

    @Test
    public void testGetoQuantityFailure() {
        int unexpectedQuantity = 10;
        when(order.getoQuantity()).thenReturn(5);
        int actualQuantity = order.getoQuantity();
        assertNotEquals(unexpectedQuantity, actualQuantity, "Unexpected quantity matches actual quantity");
    }
}
