// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import java.util.Date;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@ExtendWith(SpringExtension.class)
public class Orders_getOrderDate_c032551e3e_Test {

    @InjectMocks
    private Orders orders;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
        orders.setOrderDate(new Date());
    }

    @Test
    public void testGetOrderDate() {
        Date date = orders.getOrderDate();
        assertNotNull(date, "Order date should not be null");
    }
    
    @Test
    public void testGetOrderDateFailure() {
        orders.setOrderDate(null);
        Date date = orders.getOrderDate();
        assertNull(date, "Order date should be null");
    }
}
