// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Orders_getoPrice_5561eedf69_Test {

    private Orders order;

    @BeforeEach
    public void setUp() {
        order = new Orders();
    }

    @Test
    public void testGetoPrice_WithPositivePrice() {
        double expectedPrice = 199.99;
        order.setoPrice(expectedPrice);

        double actualPrice = order.getoPrice();

        assertEquals(expectedPrice, actualPrice, "The actual price does not match the expected price");
    }

    @Test
    public void testGetoPrice_WithZeroPrice() {
        double expectedPrice = 0.0;
        order.setoPrice(expectedPrice);

        double actualPrice = order.getoPrice();

        assertEquals(expectedPrice, actualPrice, "The actual price does not match the expected price");
    }
}
