// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class Orders_getUser_ce76c401a0_Test {

    @InjectMocks
    Orders orders;

    @Mock
    User user;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetUser_success() {
        when(user.getU_id()).thenReturn(1);
        when(user.getUname()).thenReturn("Test User");
        orders.setUser(user);
        User result = orders.getUser();
        assertNotNull(result);
        assertEquals(1, result.getU_id());
        assertEquals("Test User", result.getUname());
    }

    @Test
    public void testGetUser_null() {
        orders.setUser(null);
        User result = orders.getUser();
        assertNull(result);
    }
}
