// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import java.util.Date;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;

public class Orders_getoName_25dcc57c9b_Test {

    @Test
    public void testGetoName_success() {
        // Given
        Orders order = new Orders();
        String expectedName = "testOrder";
        order.setoName(expectedName);

        // When
        String actualName = order.getoName();

        // Then
        assertNotNull(actualName);
        assertEquals(expectedName, actualName);
    }

    @Test
    public void testGetoName_null() {
        // Given
        Orders order = new Orders();

        // When
        String actualName = order.getoName();

        // Then
        assertEquals(null, actualName);
    }
}
