// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import java.util.Date;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class Orders_getOrderDate_c032551e3e_Test {

    @InjectMocks
    private Orders orders;

    @Test
    public void testGetOrderDate_Success() {
        Date mockDate = Mockito.mock(Date.class);
        orders.setOrderDate(mockDate);
        Date result = orders.getOrderDate();

        Assertions.assertNotNull(result, "Expected not null");
        Assertions.assertEquals(mockDate, result, "Expected and actual dates should be same");
    }

    @Test
    public void testGetOrderDate_Null() {
        Date result = orders.getOrderDate();

        Assertions.assertNull(result, "Expected null as order date is not set");
    }
}
