// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Orders_setUser_e2a2590c5f_Test {

    @Mock
    private Order order;

    @Mock
    private User user;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetUser_Success() {
        order.setUser(user);
        assertEquals(user, order.getUser());
    }

    @Test
    public void testSetUser_Null() {
        order.setUser(null);
        assertNull(order.getUser());
    }
}
