// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Orders_setoName_114bba4e2d_Test {

    @Test
    public void testSetoName() {
        Orders order = new Orders();
        String expectedName = "Order1";
        order.setoName(expectedName);
        assertEquals(expectedName, order.getoName());
    }

    @Test
    public void testSetoName_Null() {
        Orders order = new Orders();
        String expectedName = null;
        order.setoName(expectedName);
        assertNull(order.getoName());
    }
}
