// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Orders_setoId_10b5d80784_Test {

    @Mock
    private Orders orders;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        orders = new Orders();
    }

    @Test
    public void testSetoId_validId() {
        int oId = 5;
        orders.setoId(oId);
        Assertions.assertEquals(oId, orders.getoId(), "The order ID should be set correctly.");
    }

    @Test
    public void testSetoId_negativeId() {
        int oId = -5;
        Assertions.assertThrows(IllegalArgumentException.class, () -> orders.setoId(oId), "The method should throw an exception when trying to set a negative order ID.");
    }
}
