// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Orders_setoName_114bba4e2d_Test {

    private Orders order;

    @BeforeEach
    public void setUp() {
        order = new Orders();
    }

    @Test
    public void testSetoName_ValidName() {
        String expectedName = "Test Order";
        order.setoName(expectedName);
        assertEquals(expectedName, order.getoName());
    }

    @Test
    public void testSetoName_EmptyName() {
        String expectedName = "";
        order.setoName(expectedName);
        assertEquals(expectedName, order.getoName());
    }

    @Test
    public void testSetoName_NullName() {
        String expectedName = null;
        order.setoName(expectedName);
        assertEquals(expectedName, order.getoName());
    }
}
