// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
public class Orders_getoName_25dcc57c9b_Test {

    @MockBean
    private Order order;

    @Test
    public void testGetoName_ValidOrderName() {
        String expectedName = "TestOrder";
        Mockito.when(order.getoName()).thenReturn(expectedName);
        String actualName = order.getoName();
        assertNotNull(actualName);
        assertEquals(expectedName, actualName, "Expected order name does not match the actual order name.");
    }

    @Test
    public void testGetoName_NullOrderName() {
        Mockito.when(order.getoName()).thenReturn(null);
        String actualName = order.getoName();
        assertEquals(null, actualName, "Order name should be null.");
    }
}
