// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import java.util.Date;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class Orders_setOrderDate_f05b775bcf_Test {

    @Mock
    User user;
    
    Orders orders;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
        orders = new Orders();
    }

    @Test
    public void testSetOrderDate() {
        Date date = new Date();
        orders.setOrderDate(date);
        Date actualDate = orders.getOrderDate();
        
        assertNotNull(actualDate, "Order date should not be null");
        assertEquals(date, actualDate, "Expected and actual order dates should match");
    }
    
    @Test
    public void testSetOrderDateWithNull() {
        orders.setOrderDate(null);
        Date actualDate = orders.getOrderDate();
        
        assertEquals(null, actualDate, "Expected and actual order dates should both be null");
    }
}
