// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import java.util.Date;

public class Orders_getTotalAmmout_24484ef500_Test {
    
    private Orders orders;
    private User user;

    @BeforeEach
    public void setup() {
        user = Mockito.mock(User.class);
        orders = new Orders();
        orders.setUser(user);
        orders.setoId(1);
        orders.setoName("Test Order");
        orders.setoPrice(100.0);
        orders.setoQuantity(2);
        orders.setOrderDate(new Date());
        orders.setTotalAmmout(200.0);
    }

    @Test
    public void testGetTotalAmount() {
        double expectedTotalAmount = 200.0;
        double actualTotalAmount = orders.getTotalAmmout();
        Assertions.assertEquals(expectedTotalAmount, actualTotalAmount);
    }

    @Test
    public void testGetTotalAmount_Failure() {
        double unexpectedTotalAmount = 300.0;
        double actualTotalAmount = orders.getTotalAmmout();
        Assertions.assertNotEquals(unexpectedTotalAmount, actualTotalAmount);
    }
}
