// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Orders_setoPrice_d23807d912_Test {

    private Orders orders;

    @BeforeEach
    public void setUp() {
        orders = new Orders();
    }

    @Test
    public void testSetoPrice_PositiveValue() {
        double oPrice = 100.50;
        orders.setoPrice(oPrice);
        assertEquals(oPrice, orders.getoPrice(), "The oPrice should have been set to the provided value");
    }

    @Test
    public void testSetoPrice_ZeroValue() {
        double oPrice = 0.0;
        orders.setoPrice(oPrice);
        assertEquals(oPrice, orders.getoPrice(), "The oPrice should have been set to the provided value");
    }
}
