// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Orders_setoPrice_d23807d912_Test {

    @Test
    public void testSetoPricePositive() {
        Order order = new Order();
        double oPrice = 100.0;
        order.setoPrice(oPrice);
        assertEquals(oPrice, order.getoPrice());
    }

    @Test
    public void testSetoPriceZero() {
        Order order = new Order();
        double oPrice = 0.0;
        order.setoPrice(oPrice);
        assertEquals(oPrice, order.getoPrice());
    }

    @Test
    public void testSetoPriceNegative() {
        Order order = new Order();
        double oPrice = -50.0;

        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            order.setoPrice(oPrice);
        });

        String expectedMessage = "Price cannot be negative";
        String actualMessage = exception.getMessage();

        assertTrue(actualMessage.contains(expectedMessage));
    }
}
