// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import java.util.Date;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Orders_setOrderDate_f05b775bcf_Test {

    private Orders orders;

    @BeforeEach
    public void setUp() {
        orders = new Orders();
    }

    @Test
    public void testSetOrderDateWithValidDate() {
        Date date = new Date();
        orders.setOrderDate(date);
        assertEquals(date, orders.getOrderDate());
    }

    @Test
    public void testSetOrderDateWithNull() {
        orders.setOrderDate(null);
        assertNull(orders.getOrderDate());
    }
}
