// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.business.entities;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Orders_getoQuantity_7e757e0c91_Test {

    private Orders orders;

    @BeforeEach
    public void setUp() {
        orders = new Orders();
    }

    @Test
    public void testGetoQuantity() {
        int expectedQuantity = 5;
        orders.setoQuantity(expectedQuantity);

        int actualQuantity = orders.getoQuantity();

        assertEquals(expectedQuantity, actualQuantity, "The expected quantity did not match the actual quantity");
    }

    @Test
    public void testGetoQuantityWhenNoQuantitySet() {
        int defaultQuantity = 0;

        int actualQuantity = orders.getoQuantity();

        assertEquals(defaultQuantity, actualQuantity, "The expected quantity did not match the actual quantity");
    }
}
